### ISSUE TITLE
Scaling of Mistake Buttons

### ISSUE THREAD

**Issue by majuwa** [kit-sdq/programming-lecture-eclipse-artemis#119]
When using font scaling the mistake buttons are too big for their container. see image
![error01](https://user-images.githubusercontent.com/2059629/135635348-370958f0-be4f-4118-bf49-9b88bb04a544.png)
er

**Comment by majuwa** [comment]
Yes, unfortunately. It gets even more confusing, since it can happen even without scaling.

**Comment by dfuchss** [comment]
I think I have to redesign the Component if I find some free time

**Comment by dfuchss** [comment]
@majuwa I assume that to be fixed in #213

This should be verified :)

**Comment by dfuchss** [comment]
It's still present. We need to find out, why this happens in Linux.
Furthermore, the Borders of the detail dialogs (Test Results Details) are not shown using Linux

(Wayland Gnome Ubuntu 22.04)

**Comment by dfuchss** [comment]
Moving to intelligrade in the future
