### ISSUE TITLE
Create Header Text (for Students) including Issue count

### ISSUE THREAD

**Issue by dfuchss** [kit-sdq/programming-lecture-eclipse-artemis#125]
See https://github.com/kit-sdq/programming-lecture-eclipse-artemis-grading/commit/7c7f6128749ac39d10cc29d020121f31f60a6479#diff-3a54f3efb6856cd995f0893e3a7545cbd22dfa30e77c82f1fc70cb0a47c3bff1R143

**Comment by Shirkanesi** [comment]
What exactly do you mean?

**Comment by dfuchss** [comment]
The text that Artemis show for overall points can be chosen freely.
Currently our grading tool creates this text here: https://github.com/kit-sdq/programming-lecture-eclipse-artemis/commit/7c7f6128749ac39d10cc29d020121f31f60a6479#diff-3a54f3efb6856cd995f0893e3a7545cbd22dfa30e77c82f1fc70cb0a47c3bff1R145

We may include the issue count of the Static Code Analysis again (but that's only a low priority) maybe we change the text to some other text in the future
