### ISSUE TITLE
`Feature Request` Allow tutors to edit annotations

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/programming-lecture-eclipse-artemis#140]
Right now there is no possibility to edit a created annotation. The only way to achive this behaviour is deleting the annotation and adding a new one.
As suggested by @dfuchss in #83 double-clicking the annotations at the bottom would be a nice way of triggering the dialog to edit the annotation.

**Comment by Shirkanesi** [comment]
This sould be quite doable, however you won't like the solution...
The eclipse-API is build a bit weird at this point, so there might be the need to use some reflections to attach the mouse-listener.

**Comment by dfuchss** [comment]
That's a bit sad but ok .. if eclipse forces a reflect access :D What's the actual problem? It's impossible to modify the default listener for this table?

**Comment by Shirkanesi** [comment]
As far as I could figure it out, the listener needs to be added to the `private MarkersTreeViewer viewer` in `ExtendedMarkersView`. However this variable is kept package-private for as far as I looked through the classes. 
I also searched for methods which might add a listener, they are (package) private as well...
Seems like reflecting is the only option :)

**Comment by Shirkanesi** [comment]
Implemented in https://github.com/kit-sdq/programming-lecture-eclipse-artemis/pull/170
