### ISSUE TITLE
Bundle SonarLint in the grading tool

### ISSUE THREAD

**Issue by Luro02** [kit-sdq/programming-lecture-eclipse-artemis#142]
Very nice plugin that lints quite a few common mistakes that might have been overseen by the tutor.

**Comment by dfuchss** [comment]
I'll discuss this option with @majuwa

**Comment by dfuchss** [comment]
I think there would be no problem in bundling sonarlint or similar tools to the eclipse product

**Comment by dfuchss** [comment]
Currently the products are already quite big. I personally think that there are no problems if you install certain plugins afterwards. For now we'll only install plugins that are really needed. 

Feel free to reopen if you think we have to integrate these plugins directly into the product :)
