### ISSUE TITLE
Custom Error Message Panel with bigger text field should have soft-wrapping

### ISSUE THREAD

**Issue by Luro02** [kit-sdq/programming-lecture-eclipse-artemis#143]
As you continue to write in the panel, it will scroll horizontally, which is kinda annoying to read:
![image](https://user-images.githubusercontent.com/24826124/145674365-71114b8c-c741-45d3-b521-f15687554cd6.png)

The "OK" Button seems to be selected by default when the panel opens, so pressing the enter key will not result in a new-line and instead will just close the panel.

The ideal solution would be to have some kind of automagical soft-wrapping that displays the remaining words in the next line if a line becomes too long, so one only has to scroll vertically and never horizontally.

**Comment by dfuchss** [comment]
* AFAIK you can use Shift+Enter to create newlines.
* Personally, I'm not a big fan of soft-wrapping. But that's only an opinion.

**Comment by Shirkanesi** [comment]
I can see both sides. Personally I'm also not the biggest fan of soft-wrapping however it could be quite useful in this case.
Soft-wrapping would be a change of one line; maybe it should be added as a config-option?

**Comment by dfuchss** [comment]
Would be ok for me 👍
