### ISSUE TITLE
Pressing "Load again" after a restart results in duplicate annotations

### ISSUE THREAD

**Issue by Luro02** [kit-sdq/programming-lecture-eclipse-artemis#144]
### To reproduce:
1. Load an already corrected submission from Artemis
2. Close Eclipse
3. Open it up again
4. Now in the Project Explorer one should still have the submission that were started before exiting eclipse
5. The grading tool is now reset and everything in Assessment has to be entered again
6. Load the Submission from Step 1 in the Backlog tab again
7. A pop-up should open up that mentions that it failed to clone the repository and one should delete it first?
8. Press OK
9. Everything in the Assessment Annotations Tab is duplicated
10. One can continue correcting the submission, but everything is duplicated now?

### What should be fixed?

I would suggest that the tool does one of the following things:
- gives a better error message that explains this issue and refuses to work with the submission that it failed to load (right now it just works?)
- handle it gracefully by using the local submission or maybe merge the remote submission with the local one? (alternatively, just deduplicate the duplicate annotations?)

**Comment by Shirkanesi** [comment]
I've got a fix for that. PR will follow soon.
