### ISSUE TITLE
Automatically load submissions for the backlog

### ISSUE THREAD

**Issue by Luro02** [kit-sdq/programming-lecture-eclipse-artemis#145]
After entering the Course, Exam and Exercise in the Assessment tab, the grading tool displays the number of started and submitted submissions, which suggests that it is loading the submissions in the background?

It would be kinda nice if one does not have to press the "Refresh Submissions" button in the Backlog tab and instead the grading tool itself loads them without user input

**Comment by Shirkanesi** [comment]
How would you do this? You need to select the Filter anyway. 
However, it would be an idea to refresh them when selecting the filter.

**Comment by Luro02** [comment]
> to refresh them when selecting the filter.

This is what I meant
