### ISSUE TITLE
Figure out how to deal with multiple projects open at once

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/programming-lecture-eclipse-artemis#154]
The plugin (currently) is designed to only support one open project at a time. 
However it is possible to have multiple participations in the workspace; the tool does not display which one is the one to assess.
The UI should display somehow, what participation is assessed at the moment.

**Comment by dfuchss** [comment]
Maybe that could be adopted from the Student view #167 . But not sure. The internal state machine of the grading tool was designed for one assessment at each time. Maybe that will be hard to rework
