### ISSUE TITLE
Autoannotate some issues based on SonarLint

### ISSUE THREAD

**Issue by Clemens-Dautermann** [kit-sdq/programming-lecture-eclipse-artemis#156]
Oftentimes while correcting I found myself just repeadedly marking the locations marked by SonarLint and doing repetetive tasks such as clicking the Interfaces button. This (and many other similar tasks) can be automated.
Suggestion:

- Include SonarLint in the grading build
- Scan the project in the beginning and automatically create Artemis annotations based on certain SonarLint rules
- Make this configurable by allowing for automatically deducing points and changing the automatic annotations using the config file or more.

**Comment by dfuchss** [comment]
Related to #142

**Comment by dfuchss** [comment]
Will be part of a practical course this term.

**Comment by dfuchss** [comment]
We'll use sonarlint to identify issues in our test framework. Therefore, this will not be part of the grading tool (for now :))
