### ISSUE TITLE
Improvement of development wiki

### ISSUE THREAD

**Issue by Clemens-Dautermann** [kit-sdq/programming-lecture-eclipse-artemis#157]
I wrote a detailed setup guide for the plugin development section. It is available [here](https://github.com/Clemens-Dautermann/eclipse-artemis-wiki/blob/master/Grading-Dev.md).

**Comment by dfuchss** [comment]
Thanks a lot! I'll take a look at it after I've returned to office :)

**Comment by dfuchss** [comment]
Actually, I've added a "Development Group" to the Updatesite https://kit-sdq.github.io/programming-lecture-eclipse-artemis/
Therefore, I'll add this to the wiki as well.

**Comment by dfuchss** [comment]
Thanks a lot. I've adopted your text and modified the wiki :)
