### ISSUE TITLE
Show tests in eclipse

### ISSUE THREAD

**Issue by Clemens-Dautermann** [kit-sdq/programming-lecture-eclipse-artemis#158]
Create a separate tab in the Artemis perspective that lists all tests and indicates how many were passed/how many failed.
I would like to have this since this is the only thing that requires me to keep the browser with Artemis open.

**Comment by Clemens-Dautermann** [comment]
Working on this [here](https://github.com/Clemens-Dautermann/programming-lecture-eclipse-artemis).

**Comment by Clemens-Dautermann** [comment]
Working on this [here](https://github.com/Clemens-Dautermann/programming-lecture-eclipse-artemis).

**Comment by Clemens-Dautermann** [comment]
Status: The new tab that will be populated once a submission is loaded has been implemented. However I am unable to obtain the information about the tests from the AssessmentController. Does anyone know how to do this?

**Comment by dfuchss** [comment]
JFYI: The view of tests is WIP for the Student edition. Maybe this can be used for the grading view as well.

**Comment by Clemens-Dautermann** [comment]
I am not familiar with the student edition. Is this the plugin being developed in the artemis-student-dev branch?

**Comment by dfuchss** [comment]
Exactly. The Plugin contains the workflow for students (actually, we hide git operations)

**Comment by Shirkanesi** [comment]
> @Clemens-Dautermann we have merged the student feature :) If you want, you can take a look at the new feature. Maybe this view can simply reused.

I think adopting this window to grading will be quite complex as it seems like it was designed purely for student-edition :(

**Comment by dfuchss** [comment]
Yes it was designed for the student tab, but I think the view should be usable. If I find some free time, I'll have a look at it.
Currently, it's defined in https://github.com/kit-sdq/programming-lecture-eclipse-artemis/blob/main/bundles/edu.kit.kastel.sdq.eclipse.student.view/src/edu/kit/kastel/eclipse/student/view/ui/ResultTab.java
