### ISSUE TITLE
[Artemis Student] HTTP 424

### ISSUE THREAD

**Issue by Clemens-Dautermann** [kit-sdq/programming-lecture-eclipse-artemis#159]
When using `viewController.getFeedbackExercise();` Artemis returns a HTTP 424. Has anyone ever seen that and knows how to solve this?

**Comment by dfuchss** [comment]
Does it occur regularly?

**Comment by dfuchss** [comment]
I'll close it for now, since I could not reproduce :) .. Feel free to reopen it.
