### ISSUE TITLE
Student Edition: Deleted files are not removed from remote on submit

### ISSUE THREAD

**Issue by b-fein** [kit-sdq/programming-lecture-eclipse-artemis#175]
Deleting files do not get added to the Git changes when clicking on the submit button. Therefore, they are not removed from the remote repository.

### Steps to reproduce
1. Start an exercise.
2. Create some new file.
3. Submit the solution.
4. Delete the previously created file.
5. Submit again.
6. Open the repository in the CLI. `git status` should show that the file has been deleted but the change is not yet marked for inclusion in the next commit.

### Additional Context
Version: Beta-Release v2022-03-25
On a Linux System

**Comment by dfuchss** [comment]
@b-fein thanks for the report. I'll have a look at it :)
