### ISSUE TITLE
`Bug`: Handle non-grading-tool feedbacks properly

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/programming-lecture-eclipse-artemis#187]
**Describe the bug**
When having a manual feedback that was not created with the grading-tool (eg +2P for any reason)
the grading tool will delete those feedbacks.

**To Reproduce**
1. Create a manual feedback using the artemis-ui
2. Open the submission in the grading-tool
3. save
4. See error (manual feedback got deleted)

**Expected behavior**
Manual feedback should not be touched (or the grading tool should convert this feedback into a custom penalty)

**Comment by dfuchss** [comment]
We have to discuss this internally (@majuwa @YvesKirschner)
This was made to ensure that the points in the grading tool are the only points. Maybe we add a feature to provide +points

**Comment by dfuchss** [comment]
We can now provide positive points. Therefore, we do not need "plain" annotations anymore :)
