### ISSUE TITLE
`Bug`: List of minor UI-Bugs

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/programming-lecture-eclipse-artemis#193]
I'll just start a discussion on minor UI-Bugs noticed while correcting. Feel free to add the ones you found down below :)

1) Line numbers are not visible by default (when using the build from github) ✅ 
2) Test-Results is not scrollable by mouse-wheel

**Comment by dfuchss** [comment]
ad 1) afaik we would have to provide a workspace if we want to set such properties.

**Comment by Shirkanesi** [comment]
> ad 1) afaik we would have to provide a workspace if we want to set such properties.
Some googleing and testing lead me to 
`EditorsUI.getPreferenceStore().setValue(AbstractDecoratedTextEditorPreferenceConstants.EDITOR_LINE_NUMBER_RULER, true);`
This actually works enables line numbers. As I can't imageine any reason for somebody to not want line-numbers, I'd suggest putting it somewhere into the logic for starting the plugin (probably just the common Activator?)

**Comment by dfuchss** [comment]
I absolutely agree on you :) I like those numbers as well. If that snipped does its job. We can easily integrate that to the plugin activator I guess (maybe we need to create an option in the settings that is enabled by default and is calls like "Eclipse Layout Optimizations" (or similar) to ensure that users are able to disable this behavior (since that would set it at any start of eclipse)

In addition, we may add some other defaults in the future as well.

**Comment by Shirkanesi** [comment]
> In addition, we may add some other defaults in the future as well.

Totaly! Maybe we'll figure out the constants for Compiler-Warnings. So we could disable complaints about "serialVersion" but enable them for potential problems.

**Comment by Shirkanesi** [comment]
ad 2): I've got told this issue purely exists on Windows.

**Comment by majuwa** [comment]
I'm not sure, whether this is a Linux only problem. In Linux (Gnome 40) the detailed view of the test results is missing the Windows-Decoration such as the title bar. Therefore, the position of the dialog cannot be moved easily. In a multiple screen setup this might problematic if the dialog open in another screen.

**Comment by Shirkanesi** [comment]
> I'm not sure, whether this is a Linux only problem. In Linux (Gnome 40) the detailed view of the test results is missing the Windows-Decoration such as the title bar. Therefore, the position of the dialog cannot be moved easily. In a multiple screen setup this might problematic if the dialog open in another screen.

Confirmed on:
- Ubuntu KDE
- Fedora KDE
- Ubuntu MATE
- Arch XFCE

Sees to be a problem for all desktop-environments.
I could NOT produce this issue on Windows.

(Note: All those test were made using `linuxserver/webtop`.)

**Comment by dfuchss** [comment]
Important here would be: Do you use Wayland or X11

**Comment by Shirkanesi** [comment]
Happens on both, X11 and Wayland.

**Comment by majuwa** [comment]
After changing the points in a custom deduction. The status bar (not sure how the element is called)  shows still the old points. However, internally it uses already correct points 
![image](https://user-images.githubusercontent.com/2059629/165538432-d2d6352b-76c7-4143-8216-9dd60ac0e780.png)

**Comment by Shirkanesi** [comment]
> After changing the points in a custom deduction. The status bar (not sure how the element is called) shows still the old points. However, internally it uses already correct points

Fixed in https://github.com/kit-sdq/programming-lecture-eclipse-artemis/pull/202

**Comment by JanWittler** [comment]
> ad 2): I've got told this issue purely exists on Windows.

Occurs on macOS (ARM) too

**Comment by Shirkanesi** [comment]
@dfuchss reopen please as only parts of the issue were solved :D
