### ISSUE TITLE
`Bug/Feature`: Bring back GitLab access-token

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/programming-lecture-eclipse-artemis#194]
During correcting it was pointed out the feature to use GitLab access-tokens was (accidentally?) removed from the grading-edition. Without this feature 2FA can not be used on the GitLab.
We should not restrict this security-feature and therefore bring back the option to use such a token.
(Probably just provide a text-box in the config where it can be entered and will be used iff not empty).

Could potentially also be added to the student-version

**Comment by dfuchss** [comment]
That was needed since it should be enforced to use the right user & password for git as well.
I think we can include another option in the settings tab that allows to set a custom password (the token) just for gitlab
