### ISSUE TITLE
`Feature`: Allow use of PAT (for 2FA) / Introduce Advanced Settings

### ISSUE THREAD

**Issue by dfuchss** [kit-sdq/programming-lecture-eclipse-artemis#196]
**Is your feature request related to a problem? Please describe.**
Followup to #194 . In the student edition we should add a checkbox "Advanced Settings" or something similar to keep the config as simple as possible for students.

**Describe the solution you'd like**
Advanced Features Property View (or Checkbox) and possibility to enter a PAT (Personal Access Token) for the GIT Interactions.

**Comment by Shirkanesi** [comment]
When refactoring parts of the config-system we might also implement a system to have settings shared between both editions.
E.g. the language-feature I'm currently working on is an example of a setting that should be shared between both versions (as checking for the language in both settings is not an option hence it is unkown which version is actually present in the PreferenceStore).
Currently I've solved this by setting the value in the common-view based on changes in both preference-pages.
Settings like the above mentioned PAT could(/should) also be shared between both editions.
