### ISSUE TITLE
`Feature`: Highlight grading buttons for penalty points whenever the max penalty per button is reached

### ISSUE THREAD

**Issue by tsaglam** [kit-sdq/programming-lecture-eclipse-artemis#199]
**Is your feature request related to a problem? Please describe.**
Sometimes it is hard to know if one should still watch out for a certain error type or not.
E.g. I already annotated error X a total of Y times, does it still make sense to look for that error?

**Describe the solution you'd like**
Whenever the max penalty is reached, the button could be highlighted, e.g. with a certain color.
Thus the reviewer knows that he may not need to look for more of these kinds of issues.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Shirkanesi** [comment]
> Thus the reviewer knows that he may not need to look for more of these kinds of issues.

I think this can be an issue. Consider a student receiving a penalty for kind of an edge-case. The assessor then marks this spot and the highlight tells them to not look for this type of issue again. 
Later the student discusses with the instructors and both agree the marked issue was not worth the penalty.
Hence the assessor did mark this type of mistake only once, the instructors might not known there are more issues of this kind in the submission, so points will be granted where they should'nt be.

Especially for cases of "bad identifiers" this mght become an issue as this cannot be decided in an objective way.

If this feature will be added, it should be communicated that one should not stop marking mistakes of this type completely.

**Comment by tsaglam** [comment]
I think this scenario you described can be the case even without this feature. Thus it should always be communicated that one should mark more than the minimal number required to reach the max penalty. However, I do not think this issue is too grave, as this tool is afaik not meant as a standalone, completely self-explicable, tool for grading.

If you guys still think this might be an issue, just consider info to the button regarding how often it was used and what the boundary for max penalty is. For example, for bad identifiers, this could be "0/3" before clicking once, but later it could be 5/3 after clicking five times. This is en par with the praktomat back in the day, if I remember correctly.

**Comment by Shirkanesi** [comment]
I thought about it, I now actually like the original idea of Timur.
However we should consider adding a small margin of like 2 and only color the button if the penalty-threshold+this margin is marked. This could help to ensure the assessor marks enough occurences of the issue.

@dfuchss do you have any other suggestions?

**Comment by tsaglam** [comment]
Closed by #332, as far as I can see.
