### ISSUE TITLE
`Feature [Student-Edition]`: Add pull-button

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/programming-lecture-eclipse-artemis#203]
**Is your feature request related to a problem? Please describe.**
Students might work on an exercise using multiple devices or doing a quick change in the online-editor.
However our current solution only allows to reset to the remote state so no real equivalent to `git pull` exists. This might be a bit annoying.

**Describe the solution you'd like**
Add a button to execute `git pull`
(Actually we might want something like `git pull --rebase=false --no-gpg-sign` to make sure nothing breaks if people have an unexpected .gitconfig)

**Describe alternatives you've considered**
\-

**Comment by dfuchss** [comment]
How would you handle merge conflicts ?

**Comment by dfuchss** [comment]
Yes, we have to think about it ..
