### ISSUE TITLE
`Bug`: Annotations partially not displayed in the Online-Editor

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/programming-lecture-eclipse-artemis#205]
**Describe the bug**
Looking back on Grading of WS2021/22 I've noticed annotations not being visible in the Online-Editor but in the list of feedbacks provided by Artemis.

This might be related to https://github.com/kit-sdq/programming-lecture-eclipse-artemis/pull/200 even though I could'nt find the connection between which feedback works and which doesn't.
It could also be an issue on Artemis' side. We should investigate this further.

**To Reproduce**
1. Grade a task (currently only ever noticed for exams)
2. Look at your annotations in the Online-Editor
3. Some annotations might not be visible in the editor. (But present in the feedback-list, the JSON and the responses from Artemis-API)

**Expected behavior**
Annotations should be visible

**Additional context**
As this issue seems to be not reproducable in a consistent way, one should always remember to look for this issue while testing other functionality. We might find a pattern over time.
Also handeling the students complaints for the current exam might be a good time to quickly look for this issue (if a complaint is against a feedback that is not visible in the editor. If so, please note down the submission and the missing feedback somewhere, so further investigations can be done based on this data.)

**Comment by dfuchss** [comment]
Are these annotations in the same line ?

**Comment by dfuchss** [comment]
Bug of Artemis :) 
https://github.com/ls1intum/Artemis/issues/5030
