### ISSUE TITLE
`Bug`: Artemis 5.8.0 breaks the development-version of the Grading-Plugin

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/programming-lecture-eclipse-artemis#209]
### Describe the bug

In https://github.com/ls1intum/Artemis/pull/4947 a pom.xml was added to the assignment-repositories.
This seems to break the import of the project into our grading tool.

This sadly also breaks the student-edition.

### Describe how to reproduce

1. Choose an exercise on the artemis-test instance. (Generated with Artemis 5.8.0)
2. Open using the grading-tool
3. see project sources not being picked up as java-sources

### Expected behavior

Everything should import normaly

### Environment

Confirmed on: 
Artemis >= 5.8.0

Might actually happen on (needs to be tested): 
Artemis >= 5.7.4

**Comment by Shirkanesi** [comment]
@dfuchss prio:HIGH

**Comment by Shirkanesi** [comment]
Ok, I've tried a bit around. Turns out this problem only happens for the `runtime-EclipseApplication`. Build products do still work. Might just be an issue with the dev-dependencies.

Seems like we are still able to use the tool in production.

**Comment by dfuchss** [comment]
Is this issue still present? This should actually work since the maven nature is also present for the student edition afaik

**Comment by dfuchss** [comment]
I cannot reproduce the issue:
Maybe you haven't m2e in your running "inner" eclipse?

![image](https://user-images.githubusercontent.com/22198798/167282825-3a2636a8-f2c9-45cd-a585-37f46f698389.png)


I've added m2e to the developer resources in 
19fd0fe - Add m2e Feature to development

**Comment by Shirkanesi** [comment]
> Maybe you haven't m2e in your running "inner" eclipse?
> I've added m2e to the developer resources

Thanks. Resolved the issue.
