### ISSUE TITLE
Add other defaults for the eclipse workspace

### ISSUE THREAD

**Issue by dfuchss** [kit-sdq/programming-lecture-eclipse-artemis#214]
> In addition, we may add some other defaults in the future as well.

Totaly! Maybe we'll figure out the constants for Compiler-Warnings. So we could disable complaints about "serialVersion" but enable them for potential problems.

_Originally posted by @Shirkanesi in https://github.com/kit-sdq/programming-lecture-eclipse-artemis/issues/193#issuecomment-1103694001_

**Comment by Shirkanesi** [comment]
To keep track of the modifications: https://github.com/kit-sdq/programming-lecture-eclipse-artemis/pull/221 (initial work on the default-preferences for eclipse JDT)

**Comment by dfuchss** [comment]
Closing for now. If we need other settings, reopen or create new issue :)
