### ISSUE TITLE
Migrate Documentation to Sphinx

### ISSUE THREAD

**Issue by dfuchss** [kit-sdq/programming-lecture-eclipse-artemis#216]
### Describe the solution you'd like

Since PRs are not possible to the Wiki function of GitHub, we should move the documentation to a separate repository (or to the a docs folder (but that will interfere with the update site))

Then something like sphinx would be usable.

**Comment by Shirkanesi** [comment]
Technically there could also be an external repo for the documentation containing an action to sync the master-branch with `git@github.com:kit-sdq/programming-lecture-eclipse-artemis.wiki.git` in order to update the documentation in the current project.

**Comment by dfuchss** [comment]
Documentation is moved to https://github.com/kit-sdq/programming-lecture-eclipse-artemis.docs
