### ISSUE TITLE
Handle Complaints directly in the Grading Tool

### ISSUE THREAD

**Issue by dfuchss** [kit-sdq/programming-lecture-eclipse-artemis#219]
### Describe the solution you'd like

I want to handle complaints directly in the grading tool.

**Comment by Shirkanesi** [comment]
This feature should also provide a way to "preview" a complaint without locking it (the API supports this)

**Comment by Shirkanesi** [comment]
Future Work:
Allow students to create complaints in the grading tool with direct references to specific penalties.
