### ISSUE TITLE
`Feature`: Support additive feedback

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/programming-lecture-eclipse-artemis#220]
### Is your feature request related to a problem?

Currently the tool only allows do correct in a subtractive way. However there is no reason to not support additive grading.

This is partially possible (tested with the current development-version 2.2.0), only serialization creates weird texts for the annotations; points are already calculated correctly.

### Describe the solution you'd like

Support additive grading

**Comment by dfuchss** [comment]
I'll have a look at is and rework the penalty mechanisms maybe I'll configure some visualization in the UI as well .. this should be rather easy :)
