### ISSUE TITLE
`Feature` [Grading]: Include allowed exercises in grading-config

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/programming-lecture-eclipse-artemis#229]
### Is your feature request related to a problem?

If differnt exercises of one assignment require different configuration-files for Artemis Grading, tutor might forget to change the config after correcting one exercise.

### Describe the solution you'd like

To prevent using the wrong configuration file for the wrong exercise, there should be a field (array of numbers) in the configuration listing all exercise-ids where the configuration can be used for. 
If another submission is loaded, a warning is shown.

**Comment by dfuchss** [comment]
Sounds good and easily realizable. 👍
