### ISSUE TITLE
`Bug`: Broken logic for started and submitted assesment

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/programming-lecture-eclipse-artemis#242]
### Describe the bug

Artemis Grading needs to pull information about the state of an assessment (started/saved/submitted) from multiple parts of the Artemis-API, as there is no single indicator for this state.
However, it seems like this logic is currently broken:

![grafik](https://user-images.githubusercontent.com/30196411/181595740-aa81ecdd-4344-4618-aeba-ff7518411e21.png)
![grafik](https://user-images.githubusercontent.com/30196411/181595915-651f9f83-aad8-4594-a735-092cc278f989.png)

I might look into it in the next days; not quite sure whether I'll be able to fix it soon :/

From my current investigation, I expect something changed in the response from Artemis, as the current logic uses dates of last result (or something like that) to figure out the state of the assessment.

### Expected behavior

Artemis Grading should handle this properly.

### Environment

Expected to be a bug on all platforms
- Windows
- Artemis Grading 2.4.0
- Artemis 5.9.4

**Comment by dfuchss** [comment]
If I find some time, I'll also have a look at it.
