### ISSUE TITLE
Add support for running external tools on each submission

### ISSUE THREAD

**Issue by Luro02** [kit-sdq/programming-lecture-eclipse-artemis#253]
### Is your feature request related to a problem?

As an addition to #156, it would be nice to have support in the grading tool for external programs.
Right now, the grading of assignments consists of annotating things that a computer could do instead. This will also add consistency to the grading of submissions.

For example, the usage of a for-loop that could be a for-each-loop is something that most available tools like `SonarLint`, `Qodana` or `PMD` can detect.

### Describe the solution you'd like

I would suggest the following:
- [ ] in the settings, one can add commands/programs that will be executed when a submission is opened, it could look something like this `my-command <path-to-submission>`, where `<path-to-submission>` will be filled in by the grading tool with the actual path
- [ ] the command will then output a JSON to stdout that contains all the found problems. How the JSON should look like, depends on the grading tool, which I have not looked at yet. I am thinking of something like this: `{ errorName: String, message: Optional<String>, locations: List<{ location: { start: int, length: int}, file: String }> }`, where this is repeated for each annotation that should be emitted
- [ ] note that there is support for multiple locations. It is not very useful to have 30 annotations of for example variables that are too short. Grouping them would make it easier for the student to review problems and correctors for finding false-positives in the overview

Would be nice to have, but maybe too much work:
- [ ] one could add support for a popup menu that goes through each piece of code that has been automatically annotated, so the tutor can manually look for false-positives

This design would also enable correctors to use tools like `Qodana` that can not be used in Artemis directly, because they would cost money and have very slow runtimes.

I would advise, against only adding support for a fixed number of tools that will be bundled with the grading-tool, because there are some errors that most existing tools can not find. For example, I have not yet found a tool that can detect code written in German. (Note: That this lint in particular can be reliably implemented through modern language detection libraries that use machine-learning)

### Describe alternatives you've considered

The alternative would be to not add support for it. This has the disadvantage that correctors will spend most of their time with dumb tasks that could be done by tooling, instead of looking for more complicated mistakes that can not be easily detected. Having this feature would add more consistency to the grading.

Maybe instead of directly executing the command on each submission, one could add a button for it.

**Comment by Luro02** [comment]
Yes, in an ideal world this would be the best solution. I have been testing quite a few tools in the last months and some lints have a horrible detection rate. For an automatic assessment where no human, except for the admin, can intervene or look for false-positives, it must be very reliable and this is rarely the case. (I think it would be contra-productive to let tutors also check the automatic assessments, which can afaik only be done through the artemis web interface)

For example PMD has a lint that detects when a `Scanner` has not been closed. Out of about 50 submissions that I tested, about 50% were wrong. Either the lint did not trigger or the lint did trigger on code that did close the scanner. To be fair many of them contained weird edge cases.

This is in my opinion unacceptable for automatic assessment, but for manual ones, one could easily switch to another tool that has better detection for this or just manually review false-positives.

In the future one could integrate especially reliable lints into artemis, which is afaik what is currently done.

**Comment by dfuchss** [comment]
Something similar is planned for a practical course this term :)

**Comment by dfuchss** [comment]
Autograder integration is done :) See #297
