### ISSUE TITLE
`Feature`: Enforce Version of Grading Tool in Grading Config

### ISSUE THREAD

**Issue by dfuchss** [kit-sdq/programming-lecture-eclipse-artemis#258]
### Describe the solution you'd like

Add a version glob to the configuration (e.g., `>=2.6.0`) to specify which version of the grading tool should be used. Show a warning or error if not matching.

**Comment by Shirkanesi** [comment]
Sound good. However, I expect this feature to not be used as it is similar to the possibility to specify the task in the config which is sadly not used currently.
