### ISSUE TITLE
`Bug`: Eclipse may fail to correctly identify packages

### ISSUE THREAD

**Issue by Feuermagier** [kit-sdq/programming-lecture-eclipse-artemis#270]
### Describe the bug

When starting an assessment and letting Eclipse open files automatically, Eclipse may fail to correctly identify packages. This leads to compilation errors as Eclipse thinks that the folders assignment/src should be part of the package declarations.

### Describe how to reproduce

1. Set "Open files automatically" to anything other than "None"
2. Start a new assessment and hope that you encounter the bug.

### Expected behavior

Eclipse should correctly identify all packages.

### Environment

- Windows, but the bug should occur on all platforms

**Comment by dfuchss** [comment]
Not seen for a very long time. So probably fixed :)
