### ISSUE TITLE
`Feature`: Visible difference between buttons that could be pressed and should be pressed

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/programming-lecture-eclipse-artemis#272]
### Is your feature request related to a problem?

When grading, it is quite unclear which buttons **should** be pressed (as those apply a deduction and for fairness reasons everyone should get this deduction if necessary) and which buttons **could** be pressed (giving no deduction but feedback).

### Describe the solution you'd like

Buttons which will further add to the deduced points should have a visual highlighting to make it clear those should definitely be pressed if applicable.

**Comment by dfuchss** [comment]
@Cora47 can you include this suggestion into your second work package?
