### ISSUE TITLE
`Bug`: Creating a custom annotation via the keyboard shortcut and adding a custom message lets the grading buttons disappear

### ISSUE THREAD

**Issue by Feuermagier** [kit-sdq/programming-lecture-eclipse-artemis#282]
### Describe the bug

When adding a new annotation with the keyboard shortcut and pressing Shift+Enter to open the custom message window, the buttons in the "Grading" tab disappear. They reappear when hovering over them with the cursor.

### Describe how to reproduce

1. Press Alt+Enter
2. Choose a penalty type
3. Press Shift+Enter
4. Enter a custom message and press enter
5. The buttons disappear

### Expected behavior

The buttons shouldn't disappear

### Screenshots

![ArtemisGrading_WhGv9d2nc5](https://user-images.githubusercontent.com/22750108/212727077-88a372b0-fb79-43ca-8629-98dd3d802e29.gif)

**Comment by dfuchss** [comment]
Moving to intelligrade in the future
