### ISSUE TITLE
Publish debian package on release

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/programming-lecture-eclipse-artemis#298]
### Is your feature request related to a problem?

Downloading and unpacking new versions of the tool is tedious.

### Describe the solution you'd like

During the build of the tool, a debian package could be build and published, which in turn allows quick and easy installation on debian-like systems. 

In the best case, also a debian repository could be provided.

**Comment by dfuchss** [comment]
This would be nice. Would it be possible to use the github pages as repository for debian-like packages?

**Comment by Shirkanesi** [comment]
Technically yes: https://github.com/marketplace/actions/github-pages-apt-repo
I need to think about a proper way to package it inside of an action but this should be totally possible.

However, as there is a requirement for a special folder "debian" I'm not quite sure whether this packaging should happen inside this repository or a new one. Do you have any idea?

**Comment by dfuchss** [comment]
Technically, I can create more repositories. E.g., just for the deployment. Nevertheless, I'd say that the build should be part of this repository (just the deployment location could be different)
