### ISSUE TITLE
`Feature`: Merge annotations (if they are more than X) before submitting

### ISSUE THREAD

**Issue by Luro02** [kit-sdq/programming-lecture-eclipse-artemis#326]
### Is your feature request related to a problem?

The autograder is very thorough when grading, so it produces a lot of annotations.
There can be 100+ annotations for a submission, which is a challenge for a student to review.
It becomes more likely that the student does not see important feedback or does not look through them all, which is unfortunate.

There are some lints that make sense to group like
- use format strings (`"%d%s".formatted(number, string)`),
- non-descriptive constant names
- unused code

but there are other lints like common reimplementation or use different visibility that provide individual suggestions for specific code and therefore would loose a lot of value by merging them.

A potential solution should therefore conditionally group annotations

### Describe the solution you'd like

The simplest solution I can think of, is to do the following:

The autograder emits for each annotation an id (could be a number).

Before submitting, the grading tool will
- count all annotations with the same id
- if there are more than for example 5 with the same id
- the first 4 are kept as is and the remaining are merged into one annotation
- the annotation could look like this: `"The identifier 'intField4' should not contain its type in the name. Other problems in L7, L8, L9, L10, L11."`

### Describe alternatives you've considered

The autograder merges lints for now, but this results in a few problems:
- false-positives made by the autograder are harder to find, because they might be hidden in a message and not marked in the code.
- one might think that some pieces have been forgotten by the autograder (because they are not marked)

**Comment by dfuchss** [comment]
I think we should/can redesign the way the annotations are presented in Artemis.
Actually, I would be happy if we can implement this in [Artemis4J](https://github.com/kit-sdq/artemis4j) :)
