### ISSUE TITLE
`Bug`: Custom Comment Dialog Doesn't Close

### ISSUE THREAD

**Issue by tikelespike** [kit-sdq/programming-lecture-eclipse-artemis#337]
### Describe the bug

Upon clicking the OK button of the "Create custom penalty" dialog (or pressing ENTER), the annotation is added, but the dialog does not close. When clicking the button again, it just creates more instances of that annotation which may lead to duplicates if not cautious. Note that this only happens with Custom Comments created via the ALT+ENTER menu.

### Describe how to reproduce

1. Select a line of code in the editor.
2. Press ALT+ENTER (Dialog created by clicking on the button in the Grading tab does not trigger the bug)
3. Type "custom" and select Custom Comment by pressing ENTER
4. Enter a custom message
5. Press ENTER or click on OK
6. As you will see, the dialog stays open.

### Expected behavior

In addition to creating the annotation (which works), the dialog should close.

### Screenshots

![image](https://github.com/kit-sdq/programming-lecture-eclipse-artemis/assets/85690358/caac0585-e6f2-4204-8b98-33f55bc702bb)
![image](https://github.com/kit-sdq/programming-lecture-eclipse-artemis/assets/85690358/8a12a20a-4526-4263-bb3d-b99e5aa53d69)
Clicking OK does not close the dialog (clicking the red x works though).

### Environment

- Ubuntu 20.04
- Grading Tool release v4.8.2

**Comment by dfuchss** [comment]
Anything in the log that is related to the issue :) ?

**Comment by dfuchss** [comment]
If it does not occur anymore, feel free to close the issue after grading :)

**Comment by tikelespike** [comment]
Closing this now because I can no longer reproduce the bug

**Comment by tikelespike** [comment]
Closing this now because I can no longer reproduce the bug
