### ISSUE TITLE
Feature request: Annotations with additional custom text 

### ISSUE THREAD

**Issue by moritzhertler** [kit-sdq/programming-lecture-eclipse-artemis#83]
In certain situations, the message of an existing `MistakeType` is not sufficient enough (in case one wants to explain the mistake contextually or give concrete suggestions for improvement). Rather than looking up the correct penalty and adding a custom annotation instead or adding a second annotation before or after the actual annotation, it would be nice to have the option to add custom text to any annotation. This feature could be integrated into the UI nicely in combination with #82.

**Comment by Shirkanesi** [comment]
I started experimenting around a bit. One (quite intuitive?) way would be to allow adding this text when Shift-Clicking (and/or middle-clicking) the penalty-button (basically by bringing up a dialog similar to the custom-penalty message-box). 
Attaching both messages to the Annotation seems to be quite easy.

What do you think about this approach?

In Artemis the message could look somehow like this:
![grafik](https://user-images.githubusercontent.com/30196411/144517868-ae73b878-fdd5-40bb-b8e9-9c1743688575.png)

**Comment by dfuchss** [comment]
Would be one possibility at least for the beginning! (I'm not sure whether right click or middle click of a button is intuitive :D )

Another possibility would be to double-click on the row of some annotation in the annotation list at the bottom. But as far as I remember this would be much harder to implement (but did not tried yet)

**Comment by Shirkanesi** [comment]
I think double-click on the row at the bottom is a very nice idea in general. Hence you might forget to set the penalty-points correctly. At the moment an annotation needs to be removed and added again. 
However, for me, it would be quite anoying to first create the annotation using the buttons on the right and then double-clicking at the bottom. 
Hence need to add a custom mouse-listener anyway the actual trigger (shift-click, alt-click, middle-click, ...) can be implemented almost identical anyway. I'll take a look at how this could be implemented in the next days.

**Comment by dfuchss** [comment]
Thanks a lot :) 

I think an custom mouse listener would be very good :) (In combination with the double click even better :) )

**Comment by Shirkanesi** [comment]
Addition from Tutors:
Allow pre-defined additional messages with auto-completion (defined in JSON)

**Comment by dfuchss** [comment]
Has been realized.
